{% set version = "0.6.0" %}

package:
  name: pyscenarios
  version: {{ version }}
  python_min: '3.10'

source:
  url: https://pypi.org/packages/source/p/pyscenarios/pyscenarios-{{ version }}.tar.gz
  sha256: 3d584831a187193575f13c6ca9413e79249af8f93db82b040392b8d7d7d3413e

build:
  noarch: python
  number: 2
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools >=66
    - setuptools-scm
  run:
    - python >={{ python_min }}
    - dask >=2022.4.0
    - numpy >=1.22
    - scipy >=1.7

test:
  imports:
    - pyscenarios
  requires:
    - pytest
    - python {{ python_min }}

about:
  home: https://github.com/crusaderky/pyscenarios
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: 'Python Monte Carlo Scenario Generator'

extra:
  recipe-maintainers:
    - crusaderky
