{% set version = "0.3.0" %}

package:
  name: pyscenarios
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pyscenarios/pyscenarios-{{ version }}.tar.gz
  sha256: ee38d2396959cf57be319584acd6eb1a0d0bd88374ac9f9375a292ae61e5172a

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python >=3.6
    - pip
    - setuptools
    - setuptools-scm
  run:
    - python >=3.6
    - setuptools
    - dask >=2.2
    - numba >=0.44
    - numpy >=1.15
    - pandas >=0.25
    - scipy >=1.3

test:
  imports:
    - pyscenarios
  requires:
    - pytest >=4

about:
  home: https://github.com/crusaderky/pyscenarios
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: 'Python Monte Carlo Scenario Generator'

extra:
  recipe-maintainers:
    - crusaderky
