{% set version = "0.5.0" %}

package:
  name: pyscenarios
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/p/pyscenarios/pyscenarios-{{ version }}.tar.gz
  sha256: d1d70cd1c5dfc679d90748cd30e479a065a8e78e1264a87580b9951a21fd2edf

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools >=66
    - setuptools-scm
  run:
    - python >={{ python_min }}
    - dask >=2.2
    - numba >=0.47
    - numpy >=1.16
    - scipy >=1.3

test:
  imports:
    - pyscenarios
  requires:
    - pytest
    - python {{ python_min }}

about:
  home: https://github.com/crusaderky/pyscenarios
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: 'Python Monte Carlo Scenario Generator'

extra:
  recipe-maintainers:
    - crusaderky
