{% set version = "0.2.0" %}

package:
  name: pyscenarios
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pyscenarios/pyscenarios-{{ version }}.tar.gz
  sha256: c0ccb9d00c8e30178683bec874afa898c6e3728f9708db0763a376c925daa3a2

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python>=3.5
    - pip
  run:
    - python>=3.5
    - dask>=0.17.3
    - numba>=0.34
    - numpy>=1.13
    - pandas>=0.20
    - scipy>=1.0

test:
  imports:
    - pyscenarios
  requires:
    - pytest>=3.6

about:
  home: https://github.com/crusaderky/pyscenarios
  license: APACHE-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: 'Python Monte Carlo Scenario Generator'

extra:
  recipe-maintainers:
    - crusaderky
