travis:
  secure:
    BINSTAR_TOKEN: jsd7ssZHTi4htVMe0mCdpe2fDwy3DG1cvtC4u55lrFRzGN2NkQ3xXazoCuzgXIh2cUK9Sozxg2HvfO64Vew4Em/uakrCLTFCgSsBgMPaSwyb6rG4aW/OSS4nNs0OK1ifh0jRVD0FtOSsbyA7D0nda4vKCz0+zLWtBMPy4zm+cxBTfkajUQDIAfVyyTBfUIHY7fJlZD0Tn9ESI0WRkdxqFVsz70DX4K/6lcQUFGcS1s2Y35kIRBoh36Qta+P9e8xnTQ4kfqxpwB34498yuecgF/jVjSI41ilnt0vFVkjcpXiw94UfDOv0s3U8SJOn94ObmTF/Wf+hmNSsNfuUFxE/3iKTI+0KZsRzCvaoMIaeHjtqwMpnnSy4gbSeLuONDyMnl2LBKQXa5zByBcukhl7zAtin2nnILeZABYQU4tMGj5jXLUf/TeY4av9/Q3CHFu4y1sXQm03v6aXQdpW3O70AgO2JticzWRFACo6NFd75t7oQKrgJada4yQszF+woK5+LWIm+p7U7r4zg0RlP1pq1peoYEVNc8JsUOUvYmSOH1Tp/UPwSfRHc3XBU+CTL3t4aykcxZuGpSaaKdtskwtYK3C0O+hqZWPJkDHcewTvXU3ga3F6F+OT6Eit22hSNoUedJSe4fhUM6A1yAdLey5HaplaMMBd2pLFSctdwpfVm3QI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
