travis:
  secure:
    BINSTAR_TOKEN: EZPGmMuRyrncIO9SjQ9WsqRBdn9PDPGgjUz1/euhv+2LKSG2X08JshTjMtoIfT3+0Gkcg+WviEvyKHgvBMydnMiC172K0NBEejTwcdBAIG/+cY1mL3CFLSO+Zz7P7YLTA64XtfN0w1nXPuLhzovTxUx/cE0NTqKBfxgax/EtPrR2kf3dwXHqB7C7M91YBie2uEQ/ghGOAKz+v5JAoN9fMatvKJ4GwPtZq2dBTCJSxrVee6Zk2XWqB3KsHhY9WGkSDcnun937fSjrhrNOIvKXzg2N+65D1YmPksIHphDcAzdZ9lV6QuCOYH1897wEUHgOeSc/2YwvYqmh5vJv9UCjipIxJ/OPjHvL9+QGM7yVP4+IgwfghJZ7KB6VDlUNPqCLC34DV6Bsq+ZnA9+Y/FGoMsiK/X9bMQKIkgRPjNl8hFWVbZ6mmkWltPJZmRTEPSHkcCinyW5DbrfNAWdNqwxLqKDHui5LfKWLEeSo2NeRCFtb02AcXhWGc8coWeZTyAKCIsfKyaqu8/5zA8/NPOphlhjujVNcfNBbLOwVziNIKWNq7aS55PVB6ewK/BhLKZSSey2TZj129WBKYy+c1eHqGU8sjvWkup62Avislriag6JtLmXGqletPteBOklc1UACAUkAalwBwm3D13/YHNJ/RUajGbl/wuOXcFcFoNZ0SNs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
